name: aoc-analysis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.*
  - black
  - flake8
  - isort
  - python-dotenv
  - pandas
  - geopandas
  - matplotlib-base
  - click
  - requests
  - git_root
  - tqdm
